# Generated by Django 3.1.12 on 2021-09-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=20210923),
            preserve_default=False,
        ),
    ]
